spring:
  application:
    name: config-client-bus
  cloud:
    config:
      label: master
      profile: dev
#      uri:  http://localhost:8888/
      discovery:
        enabled: true
        serviceId: config-server
    bus:
      trace:
        enabled: true 
  rabbitmq:
    host: localhost
    port: 5672
#   username:
#   password:
server:
  port: 8881
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false