eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8786
spring:
  application:
    name: zuulService
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbonService
    api-b:
      path: /api-b/**
      serviceId: feignService