server:
  port: 8771
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      homePageUrl: https://${eureka.instance.hostname}/
      
spring:
  application:
    name: helloService